server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financedb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: 5A7234753777217A25432A46294A404E635166546A576E5A7234753778217A24
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html